# Generated by Django 4.2.5 on 2023-10-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="lead_name",
            field=models.CharField(default="hanwen", max_length=100),
        ),
        migrations.DeleteModel(
            name="Leader",
        ),
    ]
