# Generated by Django 4.2.5 on 2023-10-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0003_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reciver_name",
            field=models.CharField(default="hanwen", max_length=100),
        ),
    ]
