# Generated by Django 4.2.5 on 2023-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0005_rename_reciver_name_message_receiver_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="receiver_read",
            field=models.BooleanField(default=False),
        ),
    ]
