# Generated by Django 4.2.5 on 2023-10-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0007_alter_activity_name_alter_club_name_userlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlevel",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_level",
                to="club.club",
            ),
        ),
    ]
