# Generated by Django 4.2.5 on 2023-10-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0009_club_fans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlevel",
            name="club",
        ),
        migrations.AddField(
            model_name="userlevel",
            name="club",
            field=models.ManyToManyField(related_name="club_level", to="club.club"),
        ),
    ]
