# Generated by Django 4.2.5 on 2023-10-11 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0010_remove_userlevel_club_userlevel_club"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLevel",
        ),
    ]
