# Generated by Django 4.2.5 on 2023-10-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0011_delete_userlevel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver_read",
            field=models.CharField(default="no", max_length=10),
        ),
    ]
