# Generated by Django 4.2.5 on 2023-10-13 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club", "0013_alter_activity_begin_date_alter_activity_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="leader",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
