# Generated by Django 4.2.5 on 2023-10-14 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0016_alter_advertisement_video"),
        ("club", "0016_alter_advertisement_video_alter_club_name"),
    ]

    operations = []
