# Generated by Django 4.2.5 on 2023-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="photo",
            field=models.ImageField(
                default="static/images/face.jpg", upload_to="images/%Y/%m/%d"
            ),
        ),
    ]
