# Generated by Django 4.2.5 on 2023-10-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(blank=True, default=18, max_length=20),
        ),
    ]
